import React, { useState } from 'react'
import { MouseParallax, ScrollParallax } from 'react-just-parallax' //no me salió a mano asi que tocó
import './App.css'
import Bubble from './components/Bubble/Bubble'
import ColorPicker from './components/ColorPicker/ColorPicker'
import Card from './components/Card/Card'

function App() {
  const [colors, setColors] = useState(['#662C91', '#AA73D4', '#4361EE'])

  const getRandomColor = () => {
    return colors[Math.floor(Math.random() * 3)]
  }

  const populateBG = (amount) => {
    let elems = []
    for (var i = 0; i <= amount; i++) {
      elems.push(<Bubble color={getRandomColor()} />)
    }
    return elems
  }

  const pickerCallback = (arr) => {
    setColors(arr)
  }

  return (
    <>
      <div className="bgContainer">
        <MouseParallax isAbsolutelyPositioned strength={0.025} shouldResetPosition>
          <div className="bgItems">{populateBG(50)}</div>
        </MouseParallax>
      </div>
      <ColorPicker callback={pickerCallback} />
      <ScrollParallax strength={0.6}>
        <div className="titleContainer">
          <h1 className="name">Adrián Flores</h1>
          <div className="separator"  style={{backgroundColor: colors[1]}} />
          <h2 className="personalDesc">Estudiante de Ciencias de la Computación en la UVG</h2>
        </div>
      </ScrollParallax>
      <div className="projectContainer">
        <Card title={"Simple Chat Client"} desc={"Uses our class's chat API to show and send messages in a simple chat client."} url={"nav"} colors={colors}/>
        <Card title={"Card Memory Game"} desc={"Memory game made as an entry to React."} url={"nav"} colors={colors}/>
        <Card title={"Maze Game"} desc={"A simple maze game with a layout generated by an API to showcase Storybook and React functionality."} url={"nav"} colors={colors}/>
        <Card title={"Basic Calculator"} desc={"A calculator with basic functionality made with React."} url={"nav"} colors={colors}/>
      </div>
    </>
  )
}

export default App
